---
title: "Biostats 776 Intro"
author: "Alison Lu"
date: 2021-09-03
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Background

Hello there! My name is Alison Lu and I'm a second year ScM student in the MMI department. I majored in biology and economics in undergrad and worked exclusively with STATA for a number of econ projects. I'm excited to dive into R with this course and hopefully learn some new tools I can apply to my research.

# Research

I'm currently working on an expansion microscopy project that aims to produce high resolution images of mitochondrial effects/changes after a viral infection. A number of the image processing programs I run actually use machine and deep learning to help clean everything up.

# Fun facts

1. I've won a national championship my sophomore year of college.
2. The fastest time it's taken me to solve a rubik's cube was around 30 seconds.
3. I can perform three magic tricks fairly well... and two not so well.
4. Will go to semi-extreme lengths for a good concert. Drove 3 hours to NYC one afternoon and made it back for my 9am the next day :)
5. I've "caught" a home run once at a Red Sox's game.

# Website plug

http://www.foddy.net/Athletics.html

A hilarious game to watch but quite frustrating to actually play. I tend to move the character backwards much more often than I do forwards.